#- name: Debugging some vars
#  debug:
#    msg: |
#      {{ ansible_inventory_sources[0] | dirname }}
#- meta: end_play

- name: Create temporary work directory
  tempfile:
    state: directory
    suffix: docker-compose
  register: mytemp

- name: Create data directory
  file:
    state: directory
    path: "{{ wikijs_data_dir }}/{{ item }}"
    recurse: yes
    mode: '777'
  loop:
    - cache
    - uploads
    - content

#- debug:
#    msg: |
#      {{ lookup('template', 'docker-compose.yaml.j2') }}
#      ---
#      mytemp: {{ mytemp | to_nice_yaml }}

- name: Generate docker compose file
  template:
    src: 'docker-compose.yaml.j2'
    dest: "{{ mytemp.path }}/docker-compose.yaml"

- name: Copy Dockerfile to temp
  copy:
    src: "{{ ansible_inventory_sources[0] | dirname }}/Dockerfile"
    dest: "{{ mytemp.path }}"

#- meta: end_play
#- fail:
#    msg: "I have failed you master!"

- name: Deploy wiki.js
  command: "docker-compose -f {{ mytemp.path }}/docker-compose.yaml -p {{ wikijs_project_name }} {{ item }}"
  register: my_output
  loop:
  - down
  - up -d
  - ps

- debug:
    msg: |
      ---
      my_output (with list filtered by not empty attribute 'stdout' and select only the values of 'stdout'):
      {{ my_output.results | selectattr('stdout', 'ne', '') | map(attribute='stdout') | list | to_nice_yaml }}
      ----

- include_tasks: "ansible-role-deploy/tasks/insert-user.yml"
  tags: insert-user
  